anim_preload_anim_library(playerid, animlib[]) {

	ApplyAnimation(playerid,animlib,"null",0.0,0,0,0,0,0);

}


anim_preload_anims(playerid) {

	anim_preload_anim_library(playerid, "AIRPORT");
	anim_preload_anim_library(playerid, "ATTRACTORS");
	anim_preload_anim_library(playerid, "BAR");
	anim_preload_anim_library(playerid, "BASEBALL");
	anim_preload_anim_library(playerid, "BD_FIRE");
	anim_preload_anim_library(playerid, "BEACH");
	anim_preload_anim_library(playerid, "BENCHPRESS");
	anim_preload_anim_library(playerid, "BF_INJECTION");
	anim_preload_anim_library(playerid, "BIKED");
	anim_preload_anim_library(playerid, "BIKEH");
	anim_preload_anim_library(playerid, "BIKELEAP");
	anim_preload_anim_library(playerid, "BIKES");
	anim_preload_anim_library(playerid, "BIKEV");
	anim_preload_anim_library(playerid, "BIKE_DBZ");
	anim_preload_anim_library(playerid, "BMX");
	anim_preload_anim_library(playerid, "BOMBER");
	anim_preload_anim_library(playerid, "BOX");
	anim_preload_anim_library(playerid, "BSKTBALL");
	anim_preload_anim_library(playerid, "BUDDY");
	anim_preload_anim_library(playerid, "BUS");
	anim_preload_anim_library(playerid, "CAMERA");
	anim_preload_anim_library(playerid, "CAR");
	anim_preload_anim_library(playerid, "CARRY");
	anim_preload_anim_library(playerid, "CAR_CHAT");
	anim_preload_anim_library(playerid, "CASINO");
	anim_preload_anim_library(playerid, "CHAINSAW");
	anim_preload_anim_library(playerid, "CHOPPA");
	anim_preload_anim_library(playerid, "CLOTHES");
	anim_preload_anim_library(playerid, "COACH");
	anim_preload_anim_library(playerid, "COLT45");
	anim_preload_anim_library(playerid, "COP_AMBIENT");
	anim_preload_anim_library(playerid, "COP_DVBYZ");
	anim_preload_anim_library(playerid, "CRACK");
	anim_preload_anim_library(playerid, "CRIB");
	anim_preload_anim_library(playerid, "DAM_JUMP");
	anim_preload_anim_library(playerid, "DANCING");
	anim_preload_anim_library(playerid, "DEALER");
	anim_preload_anim_library(playerid, "DILDO");
	anim_preload_anim_library(playerid, "DODGE");
	anim_preload_anim_library(playerid, "DOZER");
	anim_preload_anim_library(playerid, "DRIVEBYS");
	anim_preload_anim_library(playerid, "FAT");
	anim_preload_anim_library(playerid, "FIGHT_B");
	anim_preload_anim_library(playerid, "FIGHT_C");
	anim_preload_anim_library(playerid, "FIGHT_D");
	anim_preload_anim_library(playerid, "FIGHT_E");
	anim_preload_anim_library(playerid, "FINALE");
	anim_preload_anim_library(playerid, "FINALE2");
	anim_preload_anim_library(playerid, "FLAME");
	anim_preload_anim_library(playerid, "FLOWERS");
	anim_preload_anim_library(playerid, "FOOD");
	anim_preload_anim_library(playerid, "FREEWEIGHTS");
	anim_preload_anim_library(playerid, "GANGS");
	anim_preload_anim_library(playerid, "GHANDS");
	anim_preload_anim_library(playerid, "GHETTO_DB");
	anim_preload_anim_library(playerid, "GOGGLES");
	anim_preload_anim_library(playerid, "GRAFFITI");
	anim_preload_anim_library(playerid, "GRAVEYARD");
	anim_preload_anim_library(playerid, "GRENADE");
	anim_preload_anim_library(playerid, "GYMNASIUM");
	anim_preload_anim_library(playerid, "HAIRCUTS");
	anim_preload_anim_library(playerid, "HEIST9");
	anim_preload_anim_library(playerid, "INT_HOUSE");
	anim_preload_anim_library(playerid, "INT_OFFICE");
	anim_preload_anim_library(playerid, "INT_SHOP");
	anim_preload_anim_library(playerid, "JST_BUISNESS");
	anim_preload_anim_library(playerid, "KART");
	anim_preload_anim_library(playerid, "KISSING");
	anim_preload_anim_library(playerid, "KNIFE");
	anim_preload_anim_library(playerid, "LAPDAN1");
	anim_preload_anim_library(playerid, "LAPDAN2");
	anim_preload_anim_library(playerid, "LAPDAN3");
	anim_preload_anim_library(playerid, "LOWRIDER");
	anim_preload_anim_library(playerid, "MD_CHASE");
	anim_preload_anim_library(playerid, "MD_END");
	anim_preload_anim_library(playerid, "MEDIC");
	anim_preload_anim_library(playerid, "MISC");
	anim_preload_anim_library(playerid, "MTB");
	anim_preload_anim_library(playerid, "MUSCULAR");
	anim_preload_anim_library(playerid, "NEVADA");
	anim_preload_anim_library(playerid, "ON_LOOKERS");
	anim_preload_anim_library(playerid, "OTB");
	anim_preload_anim_library(playerid, "PARACHUTE");
	anim_preload_anim_library(playerid, "PARK");
	anim_preload_anim_library(playerid, "PAULNMAC");
	anim_preload_anim_library(playerid, "PED");
	anim_preload_anim_library(playerid, "PLAYER_DVBYS");
	anim_preload_anim_library(playerid, "PLAYIDLES");
	anim_preload_anim_library(playerid, "POLICE");
	anim_preload_anim_library(playerid, "POOL");
	anim_preload_anim_library(playerid, "POOR");
	anim_preload_anim_library(playerid, "PYTHON");
	anim_preload_anim_library(playerid, "QUAD");
	anim_preload_anim_library(playerid, "QUAD_DBZ");
	anim_preload_anim_library(playerid, "RAPPING");
	anim_preload_anim_library(playerid, "RIFLE");
	anim_preload_anim_library(playerid, "RIOT");
	anim_preload_anim_library(playerid, "ROB_BANK");
	anim_preload_anim_library(playerid, "ROCKET");
	anim_preload_anim_library(playerid, "RUSTLER");
	anim_preload_anim_library(playerid, "RYDER");
	anim_preload_anim_library(playerid, "SCRATCHING");
	anim_preload_anim_library(playerid, "SHAMAL");
	anim_preload_anim_library(playerid, "SHOP");
	anim_preload_anim_library(playerid, "SHOTGUN");
	anim_preload_anim_library(playerid, "SILENCED");
	anim_preload_anim_library(playerid, "SKATE");
	anim_preload_anim_library(playerid, "SMOKING");
	anim_preload_anim_library(playerid, "SNIPER");
	anim_preload_anim_library(playerid, "SPRAYCAN");
	anim_preload_anim_library(playerid, "STRIP");
	anim_preload_anim_library(playerid, "SUNBATHE");
	anim_preload_anim_library(playerid, "SWAT");
	anim_preload_anim_library(playerid, "SWEET");
	anim_preload_anim_library(playerid, "SWIM");
	anim_preload_anim_library(playerid, "SWORD");
	anim_preload_anim_library(playerid, "TANK");
	anim_preload_anim_library(playerid, "TATTOOS");
	anim_preload_anim_library(playerid, "TEC");
	anim_preload_anim_library(playerid, "TRAIN");
	anim_preload_anim_library(playerid, "TRUCK");
	anim_preload_anim_library(playerid, "UZI");
	anim_preload_anim_library(playerid, "VAN");
	anim_preload_anim_library(playerid, "VENDING");
	anim_preload_anim_library(playerid, "VORTEX");
	anim_preload_anim_library(playerid, "WAYFARER");
	anim_preload_anim_library(playerid, "WEAPONS");
	anim_preload_anim_library(playerid, "WUZI");
	anim_preload_anim_library(playerid, "WOP");
	anim_preload_anim_library(playerid, "GFUNK");
	anim_preload_anim_library(playerid, "RUNNINGMAN");

    return true;
}


CMD:animstop(playerid,params[])
{
	ClearAnimations(playerid);
	return 1;
}


CMD:lowthrow(playerid,params[])
{
	ApplyAnimation(playerid,"GRENADE","WEAPON_throwu",3.0,0,0,0,0,0);
	return 1;
}
//Groundkick
CMD:highthrow(playerid,params[])
{
	ApplyAnimation(playerid,"GRENADE","WEAPON_throw",4.0,0,0,0,0,0);
	return 1;
}
CMD:aim(playerid,params[])
{
	ApplyAnimation(playerid,"ped","ARRESTgun",4.0,0,1,1,1,-1);//Gunaim
	return 1;
}
CMD:chant(playerid,params[])
{
	ApplyAnimation(playerid,"RIOT","RIOT_CHANT",4.0,1,1,1,1,0);
	return 1;
}
CMD:lay2(playerid,params[])
{
	ApplyAnimation(playerid,"SUNBATHE","Lay_Bac_in",3.0,0,1,1,1,0);
	return 1;
}
CMD:lifejump(playerid,params[])
{
	ApplyAnimation(playerid,"PED","EV_dive",4.0,0,1,1,1,0);
	return 1;
}
CMD:bat(playerid,params[])
{
	ApplyAnimation(playerid,"BASEBALL","Bat_IDLE",4.0,1,1,1,1,0);
	return 1;
}
CMD:rollfall(playerid,params[])
{
	ApplyAnimation(playerid,"PED","BIKE_fallR",4.0,0,1,1,1,0);
	return 1;
}
CMD:reload(playerid,params[])
{
	ApplyAnimation(playerid,"UZI","UZI_reload",4.0,0,0,0,0,0);
	return 1;
}
CMD:groundsit(playerid,params[])
{
	ApplyAnimation(playerid,"BEACH","ParkSit_M_loop",4.0,1,0,0,0,0);//Sit
	return 1;
}
CMD:medic(playerid,params[])
{
	ApplyAnimation(playerid,"MEDIC","CPR",4.0,0,0,0,0,0);
	return 1;
}
CMD:push(playerid,params[])
{
	ApplyAnimation(playerid,"GANGS","shake_cara",4.0,0,0,0,0,0);
	return 1;
}
CMD:handsup(playerid,params[])
{
	SetPlayerSpecialAction(playerid,SPECIAL_ACTION_HANDSUP);
	return 1;
}
CMD:fall(playerid,params[])
{
	ApplyAnimation(playerid,"PED","KO_skid_front",4.1,0,1,1,1,0);
	return 1;
}
CMD:dance(playerid,params[])
{
	new dancestyle;
	if(sscanf(params, "i", dancestyle)) return SendClientMessage(playerid,-1,"/dancestyle <1-3>");
	if(dancestyle==1)
	{
		SetPlayerSpecialAction(playerid,SPECIAL_ACTION_DANCE1);
	}
	else if(dancestyle==2)
	{
		SetPlayerSpecialAction(playerid,SPECIAL_ACTION_DANCE2);
	}
	else if(dancestyle==3)
	{
		SetPlayerSpecialAction(playerid,SPECIAL_ACTION_DANCE3);
	}
	SendClientMessage(playerid, -1, "Press ENTER / F to stop the animation.");
	return 1;
}

CMD:rap(playerid,params[])
{
	new rapstyle;
	if(sscanf(params, "i", rapstyle)) return SendClientMessage(playerid,-1,"/rap <1-3>");
	if(rapstyle==1)
	{
		ApplyAnimation(playerid,"RAPPING","RAP_A_Loop",4.0,1,1,1,1,0);
	}
	else if(rapstyle==2)
	{
		ApplyAnimation(playerid,"RAPPING","RAP_B_Loop",4.0,1,1,1,1,0);
	}
	else if(rapstyle==3)
	{
		ApplyAnimation(playerid,"RAPPING","RAP_C_Loop",4.0,1,1,1,1,0);
	}
	return 1;
}
CMD:wankoff(playerid,params[])
{
	new wankstyle;
	if(sscanf(params, "i", wankstyle)) return SendClientMessage(playerid,-1,"/wankoff <1-3>");
	if(wankstyle==1)
	{
		ApplyAnimation(playerid,"PAULNMAC","wank_in",4.0,1,1,1,1,0);
	}
	else if(wankstyle==2)
	{
		ApplyAnimation(playerid,"PAULNMAC","wank_loop",4.0,1,1,1,1,0);
	}
	else if(wankstyle==3)
	{
		ApplyAnimation(playerid,"PAULNMAC","wank_out",4.0,1,1,1,1,0);
	}
	return 1;
}
CMD:strip(playerid,params[])
{
	new stripstyle;
	if(sscanf(params, "i", stripstyle)) return SendClientMessage(playerid,-1,"/stripstyle <1-7>");
	if(stripstyle==1)
	{
		ApplyAnimation(playerid,"STRIP","strip_A",4.0,1,1,1,1,0);
	}
	else if(stripstyle==2)
	{
		ApplyAnimation(playerid,"STRIP","strip_B",4.0,1,1,1,1,0);
	}
	else if(stripstyle==3)
	{
		ApplyAnimation(playerid,"STRIP","strip_C",4.0,1,1,1,1,0);
	}
	else if(stripstyle==4)
	{
		ApplyAnimation(playerid,"STRIP","strip_D",4.0,1,1,1,1,0);
	}
	else if(stripstyle==5)
	{
		ApplyAnimation(playerid,"STRIP","strip_E",4.0,1,1,1,1,0);
	}
	else if(stripstyle==6)
	{
		ApplyAnimation(playerid,"STRIP","strip_F",4.0,1,1,1,1,0);
	}
	else if(stripstyle==7)
	{
		ApplyAnimation(playerid,"STRIP","strip_G",4.0,1,1,1,1,0);
	}
	return 1;
}
CMD:animsex(playerid,params[])
{
	new sexstyle;
	if(sscanf(params, "i", sexstyle)) return SendClientMessage(playerid,-1,"/animsex <1-8>");
	if(sexstyle==1)
	{
		ApplyAnimation(playerid,"SNM","SPANKING_IDLEW",4.0,1,1,1,1,0);
	}
	else if(sexstyle==2)
	{
		ApplyAnimation(playerid,"SNM","SPANKING_IDLEP",4.0,1,1,1,1,0);
	}
	else if(sexstyle==3)
	{
		ApplyAnimation(playerid,"SNM","SPANKINGW",4.0,1,1,1,1,0);
	}
	else if(sexstyle==4)
	{
		ApplyAnimation(playerid,"SNM","SPANKINGP",4.0,1,1,1,1,0);
	}
	else if(sexstyle==5)
	{
		ApplyAnimation(playerid,"SNM","SPANKEDW",4.0,1,1,1,1,0);
	}
	else if(sexstyle==6)
	{
		ApplyAnimation(playerid,"SNM","SPANKEDP",4.0,1,1,1,1,0);
	}
	else if(sexstyle==7)
	{
		ApplyAnimation(playerid,"SNM","SPANKING_ENDW",4.0,1,1,1,1,0);
	}
	else if(sexstyle==8)
	{
		ApplyAnimation(playerid,"SNM","SPANKING_ENDP",4.0,1,1,1,1,0);
	}
	return 1;
}
CMD:bj(playerid,params[])
{
	new bjstyle;
	if(sscanf(params, "i", bjstyle)) return SendClientMessage(playerid,-1,"/bj <1-12>");
	if(bjstyle==1)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_COUCH_START_P",4.0,1,1,1,1,0);
	}
	else if(bjstyle==2)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_COUCH_START_W",4.0,1,1,1,1,0);
	}
	else if(bjstyle==3)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_COUCH_LOOP_P",4.0,1,1,1,1,0);
	}
	else if(bjstyle==4)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_COUCH_LOOP_W",4.0,1,1,1,1,0);
	}
	else if(bjstyle==5)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_COUCH_END_P",4.0,1,1,1,1,0);
	}
	else if(bjstyle==6)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_COUCH_END_W",4.0,1,1,1,1,0);
	}
	else if(bjstyle==7)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_STAND_START_P",4.0,1,1,1,1,0);
	}
	else if(bjstyle==8)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_STAND_START_W",4.0,1,1,1,1,0);
	}
	else if(bjstyle==9)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_STAND_LOOP_P",4.0,1,1,1,1,0);
	}
	else if(bjstyle==10)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_STAND_LOOP_W",4.0,1,1,1,1,0);
	}
	else if(bjstyle==11)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_STAND_END_P",4.0,1,1,1,1,0);
	}
	else if(bjstyle==12)
	{
		ApplyAnimation(playerid,"BLOWJOBZ","BJ_STAND_END_W",4.0,1,1,1,1,0);
	}
	return 1;
}
//CELLPHONEI
CMD:cellin(playerid,params[])
{
	SetPlayerSpecialAction(playerid,SPECIAL_ACTION_USECELLPHONE);
	return 1;
}
//CELLPHONEOUT
CMD:cellout(playerid,params[])
{
	SetPlayerSpecialAction(playerid,SPECIAL_ACTION_STOPUSECELLPHONE);
	return 1;
}
//Leam
CMD:lean(playerid,params[])
{
	ApplyAnimation(playerid,"GANGS","leanIDLE",4.0,1,0,0,0,0);
	return 1;
}
//piss
CMD:piss(playerid,params[])
{
	ApplyAnimation(playerid,"PAULNMAC","Piss_in",4.0,0,0,0,0,0);
	return 1;
}
//follow
CMD:follow(playerid,params[])
{
	ApplyAnimation(playerid,"WUZI","Wuzi_follow",4.0,0,0,0,0,0);
	return 1;
}
//greet
CMD:greet(playerid,params[])
{
	ApplyAnimation(playerid,"WUZI","Wuzi_Greet_Wuzi",4.0,0,0,0,0,0);
	return 1;
}
//stand
CMD:stand(playerid,params[])
{
	ApplyAnimation(playerid,"WUZI","Wuzi_stand_loop",4.0,1,0,0,0,0);
	return 1;
}
//injured2
CMD:injured2(playerid,params[])
{
	ApplyAnimation(playerid,"SWAT","gnstwall_injurd",4.0,1,0,0,0,0);
	return 1;
}
//hitch
CMD:hitch(playerid,params[])
{
	ApplyAnimation(playerid,"MISC","Hiker_Pose",4.0,1,0,0,0,0);
	return 1;
}
//shake
CMD:shake(playerid,params[])
{
	ApplyAnimation(playerid,"GANGS","hndshkfa_swt",4.0,0,0,0,0,0);
	return 1;
}
//bitchslap
CMD:bitchslap(playerid,params[])
{
	ApplyAnimation(playerid,"MISC","bitchslap",4.0,0,0,0,0,0);
	return 1;
}
//CPR
CMD:cpr(playerid,params[])
{
	ApplyAnimation(playerid,"MEDIC","CPR",4.0,1,0,0,0,0);
	return 1;
}
CMD:gsign1(playerid,params[])
{
	ApplyAnimation(playerid,"GHANDS","gsign1",4.0,0,1,1,1,1);
	return 1;
}
CMD:gsign2(playerid,params[])
{
	ApplyAnimation(playerid,"GHANDS","gsign2",4.0,0,1,1,1,1);
	return 1;
}
CMD:gsign3(playerid,params[])
{
	ApplyAnimation(playerid,"GHANDS","gsign3",4.0,0,1,1,1,1);
	return 1;
}
CMD:gsign4(playerid,params[])
{
	ApplyAnimation(playerid,"GHANDS","gsign4",4.0,0,1,1,1,1);
	return 1;
}
CMD:gsign5(playerid,params[])
{
	ApplyAnimation(playerid,"GHANDS","gsign5",4.0,0,1,1,1,1);
	return 1;
}
//Gift
CMD:gift(playerid,params[])
{
	ApplyAnimation(playerid,"KISSING","gift_give",4.0,0,0,0,0,0);
	return 1;
}
//sit
CMD:chairsit(playerid,params[])
{
	ApplyAnimation(playerid,"PED","SEAT_idle",4.0,1,0,0,0,0);
	return 1;
}
//injured
CMD:injured(playerid,params[])
{
	ApplyAnimation(playerid,"SWEET","Sweet_injuredloop",4.0,1,0,0,0,0);
	return 1;
}
//slapass
CMD:slapped(playerid,params[])
{
	ApplyAnimation(playerid,"SWEET","ho_ass_slapped",4.0,0,0,0,0,0);
	return 1;
}
//getslapedintheass
CMD:slapass(playerid,params[])
{
	ApplyAnimation(playerid,"SWEET","sweet_ass_slap",4.0,0,0,0,0,0);
	return 1;
}
//Drunk
CMD:drunk(playerid,params[])
{
	ApplyAnimation(playerid,"PED","WALK_DRUNK",4.1,1,1,1,1,1);
	return 1;
}
//gangwalk
CMD:gangwalk(playerid,params[])
{
	ApplyAnimation(playerid,"PED","WALK_gang1",4.1,1,1,1,1,1);
	return 1;
}
//gangwalk2
CMD:gangwalk2(playerid,params[])
{
	ApplyAnimation(playerid,"PED","WALK_gang2",4.1,1,1,1,1,1);
	return 1;
}
//EatSit
CMD:eatsit(playerid,params[])
{
	ApplyAnimation(playerid,"FOOD","FF_Sit_Loop",4.0,1,0,0,0,0);
	return 1;
}
//Celebrate
CMD:celebrate(playerid,params[])
{
	ApplyAnimation(playerid,"benchpress","gym_bp_celebrate",4.0,1,0,0,0,0);
	return 1;
}
//Win1
CMD:win(playerid,params[])
{
	ApplyAnimation(playerid,"CASINO","cards_win",4.0,1,0,0,0,0);
	return 1;
}
//Win2
CMD:win2(playerid,params[])
{
	ApplyAnimation(playerid,"CASINO","Roulette_win",4.0,1,0,0,0,0);
	return 1;
}
//YES!!
CMD:yes(playerid,params[])
{
	ApplyAnimation(playerid,"CLOTHES","CLO_Buy",4.0,1,0,0,0,0);
	return 1;
}
//Dealer2
CMD:deal2(playerid,params[])
{
	ApplyAnimation(playerid,"DEALER","DRUGS_BUY",4.0,1,0,0,0,0);
	return 1;
}
//Thank
CMD:thankyou(playerid,params[])
{
	ApplyAnimation(playerid,"FOOD","SHP_Thank",4.0,1,0,0,0,0);
	return 1;
}
//Invite1
CMD:invite1(playerid,params[])
{
	ApplyAnimation(playerid,"GANGS","Invite_Yes",4.1,0,1,1,1,1);
	return 1;
}
//Invite2
CMD:invite2(playerid,params[])
{
	ApplyAnimation(playerid,"GANGS","Invite_No",4.1,0,1,1,1,1);
	return 1;
}
//Celebrate2
CMD:celebrate2(playerid,params[])
{
	ApplyAnimation(playerid,"GYMNASIUM","gym_tread_celebrate",4.0,1,0,0,0,0);
	return 1;
}
//Sit
CMD:sit(playerid,params[])
{
	ApplyAnimation(playerid,"INT_OFFICE","OFF_Sit_Type_Loop",4.0,1,0,0,0,0);
	return 1;
}
//Scratch
CMD:scratch(playerid,params[])
{
	ApplyAnimation(playerid,"MISC","Scratchballs_01",4.0,1,0,0,0,0);
	return 1;
}
//PlaceaBomb
CMD:bomb(playerid,params[])
{
	ClearAnimations(playerid);
	ApplyAnimation(playerid,"BOMBER","BOM_Plant",4.0,0,0,0,0,0);//PlaceBomb
	return 1;
}
//PoliceArrest
CMD:getarrested(playerid,params[])
{
	ApplyAnimation(playerid,"ped","ARRESTgun",4.0,0,1,1,1,-1);//GunArrest
	return 1;
}
//Laugh
CMD:laugh(playerid,params[])
{
	ApplyAnimation(playerid,"RAPPING","Laugh_01",4.0,0,0,0,0,0);//Laugh
	return 1;
}
//RobLookout
CMD:lookout(playerid,params[])
{
	ApplyAnimation(playerid,"SHOP","ROB_Shifty",4.0,0,0,0,0,0);//RobLookout
	return 1;
}
//RobThreat
CMD:robman(playerid,params[])
{
	ApplyAnimation(playerid,"SHOP","ROB_Loop_Threat",4.0,1,0,0,0,0);//Rob
	return 1;
}
//Armscrossed
CMD:crossarms(playerid,params[])
{
	ApplyAnimation(playerid,"COP_AMBIENT","Coplook_loop",4.0,0,1,1,1,-1);//Armscrossed
	return 1;
}
//Armscrossed2
CMD:crossarms2(playerid,params[])
{
	ApplyAnimation(playerid,"DEALER","DEALER_IDLE",4.0,0,1,1,1,-1);//Armscrossed2
	return 1;
}
//Armscrossed3
CMD:crossarms3(playerid,params[])
{
	ApplyAnimation(playerid,"DEALER","DEALER_IDLE_01",4.0,0,1,1,1,-1);//Armscrossed3
	return 1;
}
//LayDown
CMD:lay(playerid,params[])
{
	ApplyAnimation(playerid,"BEACH","bather",4.0,1,0,0,0,0);//Laydown
	return 1;
}
//TakeCover
CMD:hide(playerid,params[])
{
	if(GetPlayerState(playerid)!=PLAYER_STATE_DRIVER&&GetPlayerState(playerid)!=PLAYER_STATE_PASSENGER)
	{
		ApplyAnimation(playerid,"ped","cower",3.0,1,0,0,0,0);//TakingCover
		return 1;
	}
	return 1;
}
//Vomit
CMD:vomit(playerid,params[])
{
	ApplyAnimation(playerid,"FOOD","EAT_Vomit_P",3.0,0,0,0,0,0);//VomitBAH!
	return 1;
}
//EatBurger
/*CMD:eat(playerid,params[])
{
	ApplyAnimation(playerid,"FOOD","EAT_Burger",3.0,0,0,0,0,0);//EatBurger
	return 1;
}*/
//Wave
CMD:wave(playerid,params[])
{
	ApplyAnimation(playerid,"ON_LOOKERS","wave_loop",4.0,1,0,0,0,0);//Wave
	return 1;
}
//Dealer
CMD:deal(playerid,params[])
{
	ApplyAnimation(playerid,"DEALER","DEALER_DEAL",4.0,1,0,0,0,0);//DealDrugs
	return 1;
}
//CrackDieing
CMD:crack(playerid,params[])
{
	ApplyAnimation(playerid,"CRACK","crckdeth2",4.0,1,0,0,0,0);//DieingofCrack
	return 1;
}
//MaleSmoking
CMD:smokem(playerid,params[])
{
	ApplyAnimation(playerid,"SMOKING","M_smklean_loop",4.0,1,0,0,0,0);//Smoke
	return 1;
}
//FemaleSmoking
CMD:smokef(playerid,params[])
{
	ApplyAnimation(playerid,"SMOKING","F_smklean_loop",4.0,1,0,0,0,0);//FemaleSmoking
	return 1;
}
//MaleSit
CMD:msit(playerid,params[])
{
	ApplyAnimation(playerid,"BEACH","ParkSit_M_loop",4.0,1,0,0,0,0);//MaleSit
	return 1;
}
//FemaleSit
CMD:fsit(playerid,params[])
{
	ApplyAnimation(playerid,"BEACH","ParkSit_W_loop",4.0,1,0,0,0,0);//FemaleSit
	return 1;
}
//IdleChat
CMD:chatnow(playerid,params[])
{
	ApplyAnimation(playerid,"PED","IDLE_CHAT",4.1,1,1,1,1,1);
	return 1;
}
//Fucku
CMD:fucku(playerid,params[])
{
	ApplyAnimation(playerid,"PED","fucku",4.0,0,0,0,0,0);
	return 1;
}
//TaiChi
CMD:taichi(playerid,params[])
{
	ApplyAnimation(playerid,"PARK","Tai_Chi_Loop",4.0,1,0,0,0,0);
	return 1;
}
//ChairSit
CMD:chairsit2(playerid,params[])
{
	ApplyAnimation(playerid,"BAR","dnk_stndF_loop",4.0,1,0,0,0,0);
	return 1;
}
//Kiss
CMD:kiss(playerid,params[])
{
	ApplyAnimation(playerid,"KISSING","Playa_Kiss_01",4.0,0,0,0,0,0);
	return 1;
}
//Relax
CMD:relax(playerid,params[])
{
	ApplyAnimation(playerid,"BEACH","Lay_Bac_Loop",4.0,1,0,0,0,0);
	return 1;
}
